language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r tests/requirements.txt
script:
- bash ./runtest.sh
deploy:
  - provider: pypi
    user: codeskyblue
    password:
      secure: L/fv5qfwpoRjXfL4CHBiTIGKQhSK1d8thCzZxTpU8+vLq3DJKcsAIckN779tannA+tjGq777vVd+WJaVziTQREzxFeWAH1uNhcxqQC4/BHpT5GAKY+BF1cXJIFYO7rXENtUTpVsmRfU7vl45DXRLgcEbCN+bLpz7WjgkvOHPpT3nFy6OFjngg8kK8SXZSE0BL+N8WWQSMO8l0Kiob+BxRKa3jnY2i4Ao+eMpczFxO6dU4gkPrv/EVsADqyHs4GFLEP9V0ej1AcPHjjOfO1KPE8JiUhVcnsAbOycaoHpw85IJgXu3XKVZCrvi+92fpKa36L5fuS8lKQT0MW+7pO2l3DINbEoxM9qAEclBGH7CuYegH5KYCHDG9K6psK2jzJ3SK9S342oc2cjIB1yu86+VJrgyd455PoW9o3qVMHINh/4T+9qUJn0fjzc0OyVaZawWxMrWV7La9m9ikoxuGnX3A0AnQgnHtOlelk/CO9PxaPThWlzuomzr6y6srNzNjQpZBHm+vHHVL8W1VvGMbAPNZNrUyoPf5XQgsHIBNaHDXHtYwggaQDtm+D7dFx23gbq0Dk787g9hYiJCE9HHc7NBkSh/FP3/Dgln8XKvuLcGI7cQh70Vf8yiFQsRhLDUIcy6dXQQp37kYF5vhOJx5CB/bjC9UBWu252uiiUZCkpCAgo=
    distributions: sdist bdist_wheel
  - provider: pypi
    user: codeskyblue
    password:
      secure: L/fv5qfwpoRjXfL4CHBiTIGKQhSK1d8thCzZxTpU8+vLq3DJKcsAIckN779tannA+tjGq777vVd+WJaVziTQREzxFeWAH1uNhcxqQC4/BHpT5GAKY+BF1cXJIFYO7rXENtUTpVsmRfU7vl45DXRLgcEbCN+bLpz7WjgkvOHPpT3nFy6OFjngg8kK8SXZSE0BL+N8WWQSMO8l0Kiob+BxRKa3jnY2i4Ao+eMpczFxO6dU4gkPrv/EVsADqyHs4GFLEP9V0ej1AcPHjjOfO1KPE8JiUhVcnsAbOycaoHpw85IJgXu3XKVZCrvi+92fpKa36L5fuS8lKQT0MW+7pO2l3DINbEoxM9qAEclBGH7CuYegH5KYCHDG9K6psK2jzJ3SK9S342oc2cjIB1yu86+VJrgyd455PoW9o3qVMHINh/4T+9qUJn0fjzc0OyVaZawWxMrWV7La9m9ikoxuGnX3A0AnQgnHtOlelk/CO9PxaPThWlzuomzr6y6srNzNjQpZBHm+vHHVL8W1VvGMbAPNZNrUyoPf5XQgsHIBNaHDXHtYwggaQDtm+D7dFx23gbq0Dk787g9hYiJCE9HHc7NBkSh/FP3/Dgln8XKvuLcGI7cQh70Vf8yiFQsRhLDUIcy6dXQQp37kYF5vhOJx5CB/bjC9UBWu252uiiUZCkpCAgo=
    distributions: sdist bdist_wheel
    on:
      tags: true
